### PR TITLE
Add latest cycle to graph, add services.mozilla.com

### PR DESCRIPTION
**Pull request by monicachew**
@mozkeeler ready for review. This is already pushed to http://people.mozilla.org/~mchew/pinning_dashboard/.

### CODE REVIEW

**Comment by jcjones** [comment]
It looks pretty clear to me. +2?

**Comment by monicachew** [comment]
What's +2?

**Comment by jcjones** [comment]
It's better than +1, of course, and far better than -1.

**Comment by monicachew** [comment]
Ha! In that case, I will merge :)

**Comment by jcjones** [comment]
It's a reference to [Gerrit](https://gerrit-documentation.storage.googleapis.com/Documentation/2.9.1/config-labels.html#label_Code-Review) and equivalent to Ship It in Reviewboard. 
I see github also uses an emoticon for it: :+1:

**Pull request merged**
